export const json={
  'MEWS表单关联':require('@/icons/home-icon/MEWS表单关联.png'),
  'MEWS评分监护方案':require('@/icons/home-icon/MEWS评分监护.png'),
  'MEWS评分规则':require('@/icons/home-icon/MEWS评分规则.png'),
  'MEWS表单关联部门':require('@/icons/home-icon/MEWS评分规则.png'),
  'pda表单配置':require('@/icons/home-icon/PDA表单配置.png'),
  '事件设置':require('@/icons/home-icon/事件设置.png'),
  '交接班排序方式':require('@/icons/home-icon/交接班排序方式.png'),
  '任务日志':require('@/icons/home-icon/任务日志.png'),
  '任务管理':require('@/icons/home-icon/任务管理.png'),
  '医院信息':require('@/icons/home-icon/医院信息.png'),
  '员工信息':require('@/icons/home-icon/员工信息.png'),
  '大屏交接班科室配置':require('@/icons/home-icon/大屏交接班科室配置.png'),
  '字典管理':require('@/icons/home-icon/字典管理.png'),
  '宣教模板':require('@/icons/home-icon/宣教模板.png'),
  '床位信息':require('@/icons/home-icon/床位信息.png'),
  '应用授权':require('@/icons/home-icon/应用授权.png'),
  '护理事件':require('@/icons/home-icon/护理事件.png'),
  '护理任务':require('@/icons/home-icon/护理任务 .png'),
  '护理等级':require('@/icons/home-icon/护理等级.png'),
  '护理记录':require('@/icons/home-icon/护理记录.png'),
  '护理评估':require('@/icons/home-icon/护理评估.png'),
  '护理诊断':require('@/icons/home-icon/护理诊断.png'),
  '操作日志':require('@/icons/home-icon/操作日志.png'),
  '模块管理':require('@/icons/home-icon/模块管理.png'),
  '消息管理':require('@/icons/home-icon/消息管理.png'),
  '版本管理':require('@/icons/home-icon/版本管理.png'),
  '病区动态数据库配置':require('@/icons/home-icon/病区动态数据库配置.png'),
  '病区动态显示配置':require('@/icons/home-icon/病区动态显示配置.png'),
  '登录日志':require('@/icons/home-icon/登录日志.png'),
  '科室信息':require('@/icons/home-icon/科室信息.png'),
  '表单关联部门':require('@/icons/home-icon/表单关联部门.png'),
  '角色管理':require('@/icons/home-icon/角色管理.png'),
  '诊疗组':require('@/icons/home-icon/诊疗组.png'),
  '通讯录':require('@/icons/home-icon/通讯录.png'),
  '附件管理':require('@/icons/home-icon/附件管理.png')
}

export default json
